- name: play-1
  hosts: localhost
  tasks:
  - name: play-1 and task-1
    ansible.builtin.degub: #here debug is used to print the message
      msg: "hello i am from play-1 and task-1"

- name: play-2
  hosts: localhost
  tasks:
  - name: play2 and task 2
    ansible.builtin.debug: #Debug module is nothing but echo
      msg: "hello iam from play2 and task 2"