- name: variables
  hosts: localhost
  vars: #play level variable
    course: "Ansible"
    who: "iam"
  tasks:
  - name: print the information
    vars: #Task level variables to override the inheritence values
      course: "Devops"
    ansible.builtin.debug:
      msg: "hi {{who}} practising {{course}}"

  - name: print the information
    ansible.builtin.debug:
      msg: "hi {{who}} practising {{course}}"
      