- name: conditions
  hosts: web
  become: true
  tasks:
  - name: user exists or not
    ansible.builtin.command: id expense
    register: USER #to store the user info in register
    ignore_errors: true
  - name: print the user info
    ansible.builtin.debug:
      msg: "user info is: {{USER}}"
  - name: user add
    ansible.builtin.command: useradd expense
    when: USER.rc != 0  #here rc means exit status code
  - name: print hello
    ansible.builtin.debug:
      msg: "hello"