- name: conditions
  hosts: web
  become: true
  tasks:
  - name: user exists or not
    ansible.builtin.command: id expense
    ignore_errors: true
    registry:
    - name: USER
  - name: print the user info
    ansible.builtin.debug:
      msg: "user info is: {{USER}}"
  - name: print hello
    ansible.builtin.debug:
      msg: "hello"