- name: conditions
  hosts: web
  become: true
  tasks:
  - name: user exists or not
    ansible.builtin.command: id expense
    ignore_errors: true
  - name: print hello
    ansible.builtin.debug:
      msg: "hello"