- name: filters
  hosts: localhost
  become: true
  tasks:
  - name: print the filters information
    ansible.builtin.debug:
      msg: "Hello, {{KIYANSH  | default('GOOD MORNING')}}"
  - name: upper case
    vars:
      tool: ansible
    ansible.builtin.debug:
      msg: "we are practising {{tool | upper}} "
  - name: lower case
    vars:
      subject: DEVOPS
    ansible.builtin.debug:
      msg: "lower case is: {{subject | lower}}"
  - name: remove duplicates
    vars:
      numbers: [ 1,2,3,3,2,4,1,5 ]
    ansible.builtin.debug:
      msg: "after removing duplicates is: {{numbers | unique}}"
  - name: print min and maximum numbers
    vars:
      numbers: [ 10,20,150,250,845,999]
    ansible.builtin.debug:
      msg: "max number is: {{numbers | max}}, min number is: {{numbers | min}}"
  - name: conver dictionary/map into items/lists
    vars:
      my_dict:
        Name: Kiyansh
        course: devops
        current_tool: ansible
    ansible.builtin.debug:
      msg: "convert dictionary to lists is: {{my_dict | dict2items}} "
  - name: convert to items to dictionary
    vars:
      my_dict:
      - {'key': 'Name', 'value': 'Kiyansh'}
      - {'key': 'course', 'value': 'devops'}
      - {'key': 'current_tool', 'value': 'ansible'}
    ansible.builtin.debug:
      msg: "print the items to dict is: {{my_dict | items2dict}}"