- name: filters
  hosts: localhost
  become: true
  tasks:
  - name: print the filters information
    ansible.builtin.debug:
      msg: "Hello, {{KIYANSH  | default('GOOD MORNING')}}"
  - name: upper case
    vars:
      tool: ansible
    ansible.builtin.debug:
      msg: "we are practising {{tool | upper}} "
  - name: lower case
    vars:
      subject: DEVOPS
    ansible.builtin.debug:
      msg: "lower case is: {{subject | lower}}"